crates/hc_scaffold/src/utils.rs

Name checking - slightly prettier

---

crates/hc_scaffold/src/cli.rs

drops auto-completion of integrity zome names again

dropped auto-completion of integrity zome name

---

crates/hc_scaffold/src/generators/app/cargo.rs
crates/hc_scaffold/src/generators/dna.rs
crates/hc_scaffold/src/generators/zome.rs

Creates separate folders for integrity and coordinator zomes.
I had to merge in develop in between to make the cli work for testing.

Separate folders for integrity and coordinator zomes

---

run_test.sh
templates/vanilla/example/tests/hello-world.test.ts.hbs

Added a test for the hello-world example app and run it in CI.

added test for hello-world

---

.github/workflows/test.yaml
flake.lock
flake.nix

some suggestions for https://github.com/holochain/scaffolding/pull/116

tweaks to Update CI and flake

---

README.md
guides/contributing.md

Adding a guide with what I believe to be the simplest steps required to get started building on the Scaffolding and contributing back a PR

Add contributing guide

---

templates/svelte/web-app/ui/package.json.hbs

fixed packaging npm script in svelte template

---

Cargo.lock
Cargo.toml
flake.lock

This should be similar to https://github.com/holochain/scaffolding/pull/150

Bump to 0.2.4

---

src/cli.rs
src/file_tree.rs
src/scaffold/app.rs
src/scaffold/entry_type/fields.rs

Handle error creating linked `ActionHash` or `EntryHash` without previous entry-types existing

---

src/scaffold/zome.rs
src/scaffold/zome/coordinator.rs
src/scaffold/zome/integrity.rs
templates/vanilla/example/Cargo.toml.hbs

Remove explicit holochain_integrity_types dependency

---

src/templates.rs

fix: address file presence in choose_or_get_template options

---

src/scaffold/entry_type/fields.rs
src/utils.rs

fix: Fix conflicting enum name/  it's variants and entry type names producing broken code

---

templates/vanilla/example/ui/index.html.hbs
templates/vanilla/web-app/ui/index.html.hbs

fix: consider browsers that do not support top level await

---

src/scaffold/app/nix.rs

chore: use LTS node for happs

---

src/templates/web_app.rs
src/versions.rs
templates/lit/web-app/package.json.hbs
templates/svelte/web-app/package.json.hbs
templates/vanilla/web-app/package.json.hbs
templates/vue/web-app/package.json.hbs

Adds hc spin to develop branch, compatible with holochain 0.3.x.

Add hc-spin (develop)

---

templates/lit/web-app/tests/package.json.hbs
templates/lit/web-app/ui/package.json.hbs
templates/svelte/web-app/tests/package.json.hbs
templates/svelte/web-app/ui/package.json.hbs
templates/vanilla/example/ui/package.json.hbs
templates/vanilla/web-app/tests/package.json.hbs
templates/vanilla/web-app/ui/package.json.hbs
templates/vue/web-app/tests/package.json.hbs
templates/vue/web-app/ui/package.json.hbs

Tested with existing happs and no breaking changes were detected.
Closes #221

chore(deps): bump msgpack dependency

---

.github/workflows/test.yaml
templates/lit/web-app/.github/workflows/test.yaml.hbs
templates/svelte/web-app/.github/workflows/test.yaml.hbs
templates/vue/web-app/.github/workflows/test.yaml.hbs

chore: bump ci action versions

---

src/cli.rs

fix: Limit template matching to inbuilt templates

---

src/cli.rs

This PR makes the doc strings and warning text more descriptive

chore: improve no_ui flag documentation and warning

---

src/bin/hc-scaffold.rs

feat: colorize error messages to red

---

run_test.sh
src/cli.rs
src/scaffold/web_app/uis.rs

This PR also adds a check to ensure that the correct template gets used for an example
Closes #260

fix: infer vanilla template for hello world example

---

Cargo.lock
Cargo.toml
flake.lock
src/cli.rs

This PR fixes this error `No such file or directory (os error 2)` when running `hc-scaffold example`

fix: bug when running hello world example

---

templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.vue{{¡if}}.hbs

fix: invalid entry type fields in vue template

---

templates/custom-template/custom-template/template/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case collection_name}}.ts.hbs
templates/custom-template/custom-template/template/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/create-{{kebab_case entry_type.name}}.ts.hbs
templates/custom-template/custom-template/template/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{kebab_case (plural ..¡entry_type.name)}}-for-{{kebab_case linked_from.name}}.ts{{¡if}}{{¡each}}.hbs
templates/custom-template/custom-template/template/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}edit-{{kebab_case entry_type.name}}.ts{{¡if}}.hbs
templates/custom-template/custom-template/template/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case entry_type.name}}-detail.ts.hbs
templates/custom-template/custom-template/template/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{kebab_case (plural from_referenceable.name)}}-for-{{kebab_case to_referenceable.name}}.ts{{¡if}}.hbs
templates/custom-template/custom-template/template/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{kebab_case (plural to_referenceable.name)}}-for-{{kebab_case from_referenceable.name}}.ts{{¡if}}.hbs
templates/lit/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case collection_name}}.ts.hbs
templates/lit/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/create-{{kebab_case entry_type.name}}.ts.hbs
templates/lit/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{kebab_case (plural ..¡entry_type.name)}}-for-{{kebab_case linked_from.name}}.ts{{¡if}}{{¡each}}.hbs
templates/lit/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}edit-{{kebab_case entry_type.name}}.ts{{¡if}}.hbs
templates/lit/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case entry_type.name}}-detail.ts.hbs
templates/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{kebab_case (plural from_referenceable.name)}}-for-{{kebab_case to_referenceable.name}}.ts{{¡if}}.hbs
templates/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{kebab_case (plural to_referenceable.name)}}-for-{{kebab_case from_referenceable.name}}.ts{{¡if}}.hbs
templates/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs
templates/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/Create{{pascal_case entry_type.name}}.svelte.hbs
templates/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.svelte{{¡if}}{{¡each}}.hbs
templates/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.svelte{{¡if}}.hbs
templates/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.svelte.hbs
templates/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.svelte{{¡if}}.hbs
templates/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.svelte{{¡if}}.hbs
templates/vue/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.vue.hbs
templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/Create{{pascal_case entry_type.name}}.vue.hbs
templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.vue{{¡if}}{{¡each}}.hbs
templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.vue{{¡if}}.hbs
templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.vue.hbs
templates/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.vue{{¡if}}.hbs
templates/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.vue{{¡if}}.hbs

fix: holochain client error handling

---

.github/workflows/test.yaml
templates/custom-template/custom-template/template/web-app/.github/workflows/test.yaml.hbs
templates/generic/web-app/.github/workflows/test.yaml.hbs

Doesn't fix anything, just following what is happening in other repos to move to a recent Nix

Use latest Nix

---

run_test.sh
templates/generic/web-app/.github/workflows/test.yaml.hbs
templates/ui-frameworks/lit/web-app/ui/package.json.hbs
templates/ui-frameworks/vue/web-app/ui/package.json.hbs

fix: Missing dependency with lit template using `pnpm`

---

run_test.sh
src/scaffold/web_app/package_manager.rs
templates/generic/web-app/{{#if (eq package_manager "pnpm")}}pnpm-workspace.yaml{{¡if}}.hbs

fix: use pnpm workspace yaml file with pnpm happs

---

Cargo.lock
Cargo.toml
flake.lock
src/file_tree.rs
src/lib.rs
src/versions.rs

~Needs `@holochain/client` fix~

chore: bump holochain version

---

src/cli/web_app.rs
src/scaffold/zome.rs

feat: add fast track initial text to dna and zome prompts

---

src/cli/collection.rs
src/cli/entry_type.rs
src/cli/example.rs
src/cli/link_type.rs
src/cli/zome.rs
src/utils.rs

feat: format with rustfmt if available

---

src/scaffold/web_app.rs
templates/generic/web-app/{{#if (eq package_manager 'pnpm')}}pnpm-workspace.yaml{{¡if}}.hbs

fix: pnpm-workspace .hbs file generated on scaffolding a web-app/example using non-pnpm package manager

---

templates/custom-template/custom-template/template/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case collection_name}}.ts.hbs
templates/custom-template/custom-template/template/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{kebab_case (plural from_referenceable.name)}}-for-{{kebab_case to_referenceable.name}}.ts{{¡if}}.hbs
templates/custom-template/custom-template/template/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{kebab_case (plural to_referenceable.name)}}-for-{{kebab_case from_referenceable.name}}.ts{{¡if}}.hbs
templates/ui-frameworks/lit/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case collection_name}}.ts.hbs
templates/ui-frameworks/lit/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{kebab_case (plural ..¡entry_type.name)}}-for-{{kebab_case linked_from.name}}.ts{{¡if}}{{¡each}}.hbs
templates/ui-frameworks/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{kebab_case (plural from_referenceable.name)}}-for-{{kebab_case to_referenceable.name}}.ts{{¡if}}.hbs
templates/ui-frameworks/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{kebab_case (plural to_referenceable.name)}}-for-{{kebab_case from_referenceable.name}}.ts{{¡if}}.hbs
templates/ui-frameworks/react/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.tsx.hbs
templates/ui-frameworks/react/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.tsx{{¡if}}{{¡each}}.hbs
templates/ui-frameworks/react/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.tsx{{¡if}}.hbs
templates/ui-frameworks/react/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.tsx{{¡if}}.hbs
templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.svelte{{¡if}}{{¡each}}.hbs
templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/vue/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.vue.hbs
templates/ui-frameworks/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.vue{{¡if}}{{¡each}}.hbs
templates/ui-frameworks/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.vue{{¡if}}.hbs
templates/ui-frameworks/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.vue{{¡if}}.hbs

fix: update signal api usage in templates

---

src/scaffold/link_type.rs
src/scaffold/link_type/coordinator.rs
src/utils.rs

bug: fix hc scaffold link type issues

---

flake.nix
src/scaffold/app/nix.rs
templates/custom-template/custom-template/flake.nix

This PR improves the root nix flake as well as the ones generated by scaffolding. It introduces the following:
- Refactor hc-scaffold cranelib filters
- Update scaffolded nix flake inputs. Closes #365
Needs #372

Refactor nix flakes

---

src/cli/collection.rs
src/cli/entry_type.rs
src/cli/example.rs
src/cli/link_type.rs
src/scaffold/collection.rs
src/scaffold/entry_type.rs
src/scaffold/link_type.rs
src/templates/collection.rs
src/templates/entry_type.rs
src/templates/link_type.rs

Closes https://github.com/holochain/Components/issues/65

feat: add optional cli flag to skip test code generation

---

src/cli/collection.rs
src/cli/dna.rs
src/cli/entry_type.rs
src/cli/web_app.rs
src/cli/zome.rs
src/scaffold/entry_type/fields.rs
src/scaffold/entry_type/utils.rs
src/scaffold/link_type.rs
src/scaffold/zome.rs
src/utils.rs

feat: Re-prompt user on invalid input

---

Cargo.lock
Cargo.toml
flake.lock
src/versions.rs

And prep for a weekly (0.5) release

fix: Bump hc-spin for 0.5

---

Cargo.lock
Cargo.toml
templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/Create{{pascal_case entry_type.name}}.svelte.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.svelte{{¡if}}{{¡each}}.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.svelte.hbs
templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/web-app/ui/src/App.svelte.hbs
templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs

backport of https://github.com/holochain/scaffolding/pull/425

chore: backport svelte race condition and release 0.3000.11

---

Cargo.lock
Cargo.toml
templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/Create{{pascal_case entry_type.name}}.svelte.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.svelte{{¡if}}{{¡each}}.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.svelte.hbs
templates/ui-frameworks/svelte/example/ui/src/App.svelte.hbs
templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/web-app/ui/package.json.hbs
templates/ui-frameworks/svelte/web-app/ui/src/App.svelte.hbs
templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs

Backport #425 for Holochain 0.4.

chore: backport svelte race condition to 0.4 and release 0.4000.0-rc.1

---

.github/workflows/test.yaml
Cargo.lock
Cargo.toml
flake.lock
flake.nix
src/scaffold/app/nix.rs
src/versions.rs

- Testing templates
- Examples
#454

chore: Bump for holohcian 0.4.1

---

templates/ui-frameworks/vue/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.vue.hbs
templates/ui-frameworks/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/Create{{pascal_case entry_type.name}}.vue.hbs
templates/ui-frameworks/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.vue{{¡if}}{{¡each}}.hbs
templates/ui-frameworks/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.vue{{¡if}}.hbs
templates/ui-frameworks/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.vue.hbs
templates/ui-frameworks/vue/example/ui/src/App.vue.hbs
templates/ui-frameworks/vue/field-types/String/TextArea/is-valid.hbs
templates/ui-frameworks/vue/field-types/String/TextField/is-valid.hbs
templates/ui-frameworks/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.vue{{¡if}}.hbs
templates/ui-frameworks/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.vue{{¡if}}.hbs
templates/ui-frameworks/vue/web-app/ui/src/App.vue.hbs
templates/ui-frameworks/vue/web-app/ui/src/ClientProvider.vue.hbs
templates/ui-frameworks/vue/web-app/ui/src/clientProvider.ts.hbs
templates/ui-frameworks/vue/web-app/ui/tsconfig.app.json.hbs

Closes #459
How to test: scaffold a web app using the vue template following the get started guide. Additionally, you can also scaffold a `forum` example hApp using the vue template

chore: migrate vue templates to composition api

---

templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/Create{{pascal_case entry_type.name}}.svelte.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.svelte{{¡if}}{{¡each}}.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.svelte.hbs
templates/ui-frameworks/svelte/field-types/String/TextArea/edit/render.hbs
templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.svelte{{¡if}}.hbs
templates/ui-frameworks/svelte/web-app/ui/package.json.hbs
templates/ui-frameworks/svelte/web-app/ui/src/App.svelte.hbs
templates/ui-frameworks/svelte/web-app/ui/src/ClientProvider.svelte.hbs
templates/ui-frameworks/svelte/web-app/ui/src/main.ts.hbs
templates/ui-frameworks/vue/web-app/ui/src/App.vue.hbs

Upgrade to svelte 5

---

src/templates/helpers/merge.rs

I don't know why, these changes made in https://github.com/holochain/scaffolding/pull/467 are not in this branch anymore.

Include PR https://github.com/holochain/scaffolding/pull/467

---

templates/ui-frameworks/react/web-app/ui/package.json.hbs

chore: Bump to react v19 and update related dependencies

---

templates/generic/web-app/tests/package.json.hbs
templates/ui-frameworks/lit/web-app/ui/package.json.hbs
templates/ui-frameworks/react/web-app/ui/package.json.hbs
templates/ui-frameworks/vanilla/example/dnas/hello_world/zomes/coordinator/hello_world/Cargo.toml.hbs
templates/ui-frameworks/vanilla/example/dnas/hello_world/zomes/coordinator/hello_world/src/lib.rs.hbs
templates/ui-frameworks/vanilla/example/dnas/hello_world/zomes/integrity/hello_world/Cargo.toml.hbs
templates/ui-frameworks/vanilla/example/dnas/hello_world/zomes/integrity/hello_world/src/lib.rs.hbs
templates/ui-frameworks/vanilla/example/tests/hello-world.test.ts.hbs
templates/ui-frameworks/vanilla/example/ui/index.html.hbs
templates/ui-frameworks/vanilla/example/ui/package.json.hbs
templates/ui-frameworks/vanilla/web-app/ui/package.json.hbs
templates/ui-frameworks/vue/web-app/ui/package.json.hbs

chore: bump vite and other dev deps

---

run_test.sh
src/scaffold/link_type/coordinator.rs
templates/ui-frameworks/vanilla/example/dnas/hello_world/zomes/coordinator/hello_world/src/lib.rs.hbs

chore: add clippy checks to test script and fix existing warnings
