holochain/scaffolding

- packages/generators/src/tryorama/package.json.ts
Without this, if the test command fails (in certain ways, before running tests), tap-diff still returns zero error code, so CI is "green".
> Fail if any part of test command fails

- templates/lit/field-types/f32/Slider/edit/render.hbs
- templates/lit/field-types/u32/Slider/edit/render.hbs
Fixes two typos in templates.
In that same spot, if `initial_value_variable` is of `Option<T>` type, typescript complains because the value is possibly undefined. This PR does not address this issue.
> fixed typo in templates

- Cargo.lock
- Cargo.toml
- flake.lock
- flake.nix
- src/scaffold/app/nix.rs
- src/scaffold/zome.rs
this makes the update behavior predictable as per the original expectations.
> feat(flake): use separate input for holochain-nix-versions; deps: bump holochain

- .github/workflows/test.yaml
- flake.lock
- flake.nix
- run_test.sh
- src/scaffold/app/nix.rs
- src/versions.rs
* adapt to upstream flake changes
* bump the versions input to versions/0_2
* use nix to build scaffolding on CI, which can re-use cached
dependencies accross runs
---
> feat(flake,nix): bump to 0_2; feat(ci/test): use nix to build scaffolding

- templates/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.svelte{{¡if}}{{¡each}}.hbs
There are a couple bugs in the modified entry detail template that prevent dependent linked entries from being loaded. This fixes both bugs. Waiting for some changes from Robbie before un-drafting this.
There's a corresponding PR #120 for the `holochain-0.2` branch.
> Fix linked collection templates (for 0.1)

- templates/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.svelte{{¡if}}{{¡each}}.hbs
There are a couple bugs in the modified entry detail template that prevent dependent linked entries from being loaded. This fixes both bugs. Waiting for some changes from Robbie before un-drafting this.
There's a corresponding PR #119 for the `holochain-0.1` branch.
> Fix linked collection templates (for 0.2)

- src/scaffold/entry_type.rs
- src/scaffold/entry_type/definitions.rs
- templates/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.svelte{{¡if}}.hbs
This is not the most elegant way to do things -- it duplicates data; implementing a `filter` helper for Handlebars would've been much more elegant. But the advantage of this approach is that I can actually do it ;)
I'm working on a possibly better solution that involves writing a `filter` Handlebars helper, but I'd like to get things unblocked for the hackathon this weekend
> Prevent trailing commas when field list ends in non-widget fields in EditFoo.svelte template

- src/scaffold/app/cargo.rs
- templates/vanilla/example/Cargo.toml.hbs
Setting resolver = "2" ensures that you can import holochain test_utils as a dev-dependency in your zomes, without it breaking zome builds.
> Set rust resolver = "2" in scaffolded workspaces

- templates/lit/web-app/package.json.hbs
- templates/svelte/web-app/package.json.hbs
- templates/vue/web-app/package.json.hbs
When trying to scaffold a Holo-enabled hApp, `npm` complained that the `package.json` wasn't actual JSON. Looks like it's all about a trailing comma. This should fix it.
> Fix broken package.json for holo

- src/scaffold/app/nix.rs
There's a code comment explaining this one but I'll post the before and after here to make it clearer. When running Scaffolding inside a Git repository I was getting:
```
✔ App name (no whitespaces): · asdf
✔ Choose UI framework: · Vue
✔ Do you want to set up the holonix development environment for this project? · Yes (recommended)
Setting up nix development environment...
error: getting status of '/nix/store/2jbblm8bwyv0kq1k9r6dxy7q735d8v2c-source/asdf': No such file or directory
Error: Error setting up the nix environment
```
After this change, it tells you what the problem is:
```
✔ App name (no whitespaces): · asdf
✔ Choose UI framework: · Vue
✔ Do you want to set up the holonix development environment for this project? · Yes (recommended)
Error: Error setting up the nix environment - …
```
> Detect Nix failure due to Git conflict

- templates/vue/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.vue.hbs
- templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/Create{{pascal_case entry_type.name}}.vue.hbs
- templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.vue{{¡if}}{{¡each}}.hbs
- templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.vue{{¡if}}.hbs
- templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.vue.hbs
- templates/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.vue{{¡if}}.hbs
- templates/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.vue{{¡if}}.hbs
I ran into some trouble trying out the tutorial forum example using the Vue scaffolding instead of svelte, so I tried to fix it. I couldn't figure out a way to easily try out my fixes without making an option to not make a nix environment, which is why I added the setup_nix option, but I can revert that if it's not useful. I think I got all the places that using `error.data.data`, but there are other places that have the extra `Hash` (making `postHashHash` instead of `postHash`).
> Update vue scaffolding

- templates/vue/field-types/Timestamp/DateTimePicker/detail/render.hbs
- templates/vue/field-types/bool/Checkbox/edit/imports.hbs
Ran into these while testing another change. It looks like these types aren't covered by the automated tests, something that would be good to cover because these typescript errors prevent the app running
> Fix Vue bool and timestamp

- README.md
- guides/maintenance.md
I think this covers most things for a first pass. One notable thing missing is what 'bump the scaffolding version' means. This is an open discussion so I'll leave it out of the guide for the moment.
> Add initial maintenance guide

- Cargo.lock
- Cargo.toml
- run_test.sh
- src/scaffold/collection/coordinator.rs
- src/scaffold/entry_type/coordinator.rs
- src/scaffold/entry_type/integrity.rs
- src/scaffold/link_type/integrity.rs
- src/scaffold/zome/coordinator.rs
- templates/lit/entry-type/tests/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case entry_type.name}}.test.ts.hbs
- templates/lit/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case entry_type.name}}-detail.ts.hbs
- templates/svelte/entry-type/tests/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case entry_type.name}}.test.ts.hbs
- templates/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.svelte.hbs
- templates/vanilla/entry-type/tests/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case entry_type.name}}.test.ts.hbs
- templates/vanilla/example/dnas/hello_world/zomes/coordinator/hello_world/src/lib.rs.hbs
- templates/vue/entry-type/tests/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case entry_type.name}}.test.ts.hbs
- templates/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.vue.hbs
Summary of changes:
- Updated `syn` and `pretty-please` dependencies, this is needed to handle the new rust `let Some(_) = my_option else {};` statements.
- Disambiguated the `get_entry_type_name` getters:
- Previously, we only had a `get_entry_type_name(action_hash: ActionHash) -> ExternResult<Option<Record>>` that:
- If the entry was deleted, returned None
- Otherwise, would return the latest update for the entry
- This is bad for a couple of reasons:
- Whenever there is an update to the entry, there is actually no way for us to get the original action, so things like the creation timestamp are not accessible anymore, there are no calls that retrieve it
- Once the entry is deleted, there is no way to see it again, if you want to implement an "archived" list of entries 
- There is no …
> Refactor gets

- src/lib.rs
- src/scaffold/link_type/coordinator.rs
- src/templates.rs
- src/templates/helpers.rs
- src/templates/helpers/merge.rs
- src/templates/helpers/uniq_lines.rs
- src/versions.rs
Depends on https://github.com/holochain/scaffolding/pull/155
Refactors the `merge_scope` helper into two separate ones. [Here is the new documentation for them](https://github.com/holochain/scaffolding/blob/6f7189ea77acef72bdd867508788459e31f1ac24/src/lib.rs#L219).
Without this, the use of `merge_scope` turns out to be quite constrained in some use cases, particularly when the template needs to merge two scopes at the same level. As an example:
```ts
export class A {
}
export class B {
}
```
With the old `merge_scopes`, it was impossible to add a new function to the end of both `A` _and_ `B`, you had to choose between one of them. Now with the new helpers the templates can do it like this:
```
{{#merge previous_file_content}}
{{#match_scope "export class A"}}
{{previous_scope_content}} …
```
> Refactor merge scope

- src/cli.rs
This PR introduces a slight modification to the handling of `PathBuf` arguments in the cli. The change involves adding the `parse(from_os_str)` attribute to `PathBuf` fields to enhance the application's compatibility with file paths containing non-UTF-8 characters, particularly on Windows
> enhancement: use `parse(from_os_str)` for `PathBuf` args to handle non UTF-8 file paths on windows

- Cargo.lock
- Cargo.toml
- flake.lock
- flake.nix
- src/error.rs
- src/scaffold/collection/coordinator.rs
- src/scaffold/entry_type/coordinator.rs
- src/scaffold/entry_type/integrity.rs
- src/scaffold/link_type/coordinator.rs
- src/scaffold/zome.rs
- src/versions.rs
- templates/vanilla/example/Cargo.toml.hbs
- templates/vanilla/example/dnas/hello_world/zomes/coordinator/hello_world/src/lib.rs.hbs
- templates/vanilla/example/dnas/hello_world/zomes/integrity/hello_world/src/lib.rs.hbs
> chore: Add support for holochain `0.3`

- src/templates/web_app.rs
- src/versions.rs
- templates/lit/web-app/package.json.hbs
- templates/svelte/web-app/package.json.hbs
- templates/vanilla/web-app/package.json.hbs
- templates/vue/web-app/package.json.hbs
This PR switches to using the hc-spin CLI instead of `hc launch` by default since it provides better developer tools.
It keeps the option to run the happ in tauri explicitly via `npm run start:tauri` if that's desired.
> Use hc-spin cli (develop-0.1)

- src/versions.rs
This PR updates the holochain client version to the latest `0.3` compatible version that addresses `cell_id` being a proxy object
https://github.com/holochain/holochain-client-js/releases/tag/v0.17.0-dev.5
> chore: update holochain client version

- Cargo.lock
- Cargo.toml
- flake.lock
- templates/vanilla/example/Cargo.toml.hbs
This PR bumps holochain dependency versions to `0.2.6`
> chore: bump holochain dependency versions

- src/cli.rs
- src/scaffold/collection.rs
- src/scaffold/entry_type.rs
- src/scaffold/entry_type/fields.rs
- src/scaffold/link_type.rs
- src/templates/collection.rs
- src/templates/entry_type.rs
- src/templates/helpers.rs
- src/templates/helpers/file_exists.rs
- src/templates/link_type.rs
- templates/lit/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case collection_name}}.ts.hbs
- templates/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{kebab_case (plural from_referenceable.name)}}-for-{{kebab_case to_referenceable.name}}.ts{{¡if}}.hbs
- templates/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{kebab_case (plural to_referenceable.name)}}-for-{{kebab_case from_referenceable.name}}.ts{{¡if}}.hbs
- templates/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs
- templates/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.svelte{{¡if}}.hbs
- templates/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.svelte{{¡if}}.hbs
- templates/vue/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.vue.hbs
- templates/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.vue{{¡if}}.hbs
- templates/vue/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.vue{{¡if}}.hbs
This adds an optional flag `--no-ui` for the `link-type`, `entry-type` and `collection` commands. This flag skips `ui` generation, though the `tests` folder will still be populated with generated code
This change is non intrusive and does not break the normal behaviour of these commands
closes #186
> feat(cli): add optional flag to skip ui generation for `link-type`, `entry-type` and `collection`

- src/scaffold/entry_type/definitions.rs
- src/scaffold/entry_type/fields.rs
This PR adds a missing check for reserved Rust keywords for entry type fields
This fixes [#2679](https://github.com/holochain/holochain/issues/2769) from the holochain repo
Attempting to use a reserved keyword such as `type` now results in a more useful error
```shell
➜ hc-scaffold entry-type agent_role
Which fields should the entry contain?
✔ Choose field type: · Enum
✔ Enter the name of the enum: · AgentRoleName
✔ Enter the name of the next variant: · Admin
✔ Enter the name of the next variant: · Staff
✔ Field name: · name
✔ Should this field be visible in the UI? · yes
✔ Choose widget to render this field: · Select
✔ Choose field type: · Enum
✔ Enter the name of the enum: · AgentRoleType
✔ Enter the name of the next variant: · Swap
✔ Enter the name of the next variant: · Provider
✔ …
```
> fix: add reserved word check for entry-type field name

- templates/lit/web-app/package.json.hbs
- templates/svelte/web-app/package.json.hbs
- templates/vanilla/web-app/package.json.hbs
- templates/vue/web-app/package.json.hbs
This PR makes it possible to set the override the `AGENTS` count when running a hApp via an env var
Closes #240
> feat: add option to set agent count via env var

- flake.lock
I just run `nix flake update`, this unblocks the testing of custom templates with the new nix infrastructure.
> Update holochain source

- .github/workflows/test.yaml
- run_test.sh
- src/cli.rs
- src/lib.rs
- src/scaffold/app.rs
- src/scaffold/app/nix.rs
- src/scaffold/collection/coordinator.rs
- src/scaffold/dna/coordinator.rs
- src/scaffold/entry_type/integrity.rs
- src/scaffold/web_app.rs
- src/templates/example.rs
- src/templates/helpers.rs
- src/templates/helpers/filter.rs
- src/templates/helpers/merge.rs
- src/utils.rs
We add a --holo flag to the example subcommand.
When this flag is passed, we add holo-nixpkgs as a flake input and we add holo-dev-server to the dev shell's packages.
This PR builds on #165 that was opened by @alastairong
> Add holo-dev-server to the dev shell when --holo is passed

- templates/custom-template/custom-template/template/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case collection_name}}.ts.hbs
- templates/vue/web-app/package.json.hbs
This PR removes traces of the `file_exists` helper from the `custom-template` and the redundant `package:holo` script left over from #251
> chore: Update templates

- src/file_tree.rs
- src/utils.rs
This PR fixes #261
With regards to the scaffolding tool removing comments, I think it's easier if this is tackled in a separate PR. I have re-opened the original issue to keep track of it as well #167 since the root cause is now known.
> fix: prevent unaffected rust files from getting formatted

- templates/vue/web-app/package.json.hbs
This PR corrects an inadvertent removal of the ui start script for the vue template
Closes #283
> fix: fix vue example ui server not starting

- src/scaffold/collection/coordinator.rs
This isolated change was part of #288 where I am making a transition away from stringified rust code, which seems to cause bugs that can easily go unnoticed in code reviews
> fix: bug while scaffolding collection by author

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/templates.rs
This PR is an attempt at refactoring some the templates module, I struggled a lot with initially understanding the code and as a result would prove to be challenge in maintaining it, therefore this PR makes the following changes
- Extract the logic inside the for loop into separate functions
- Move regex strings to constants
- Prefer `match` over `if` `else if` for better readablilty
- handle errors gracefully by removing the `unwrap` calls and applying error context via anyhow where necessary, a first step in addressing #173
- perform early returns where possible
> refactor: Refactor templates module and handle unhandled errors

- templates/generic/web-app/package.json.hbs
> fix: add postinstall script for pnpm scaffolded hApps

- templates/custom-template/custom-template/template/field-types/Timestamp/DateTimePicker/edit/render.hbs
- templates/custom-template/custom-template/template/field-types/Vec/edit/render.hbs
- templates/custom-template/custom-template/template/field-types/bool/Checkbox/edit/render.hbs
- templates/ui-frameworks/lit/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case collection_name}}.ts.hbs
- templates/ui-frameworks/lit/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{kebab_case (plural ..¡entry_type.name)}}-for-{{kebab_case linked_from.name}}.ts{{¡if}}{{¡each}}.hbs
- templates/ui-frameworks/lit/field-types/Enum/Select/edit/render.hbs
- templates/ui-frameworks/lit/field-types/String/TextArea/edit/render.hbs
- templates/ui-frameworks/lit/field-types/String/TextField/edit/render.hbs
- templates/ui-frameworks/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{kebab_case (plural from_referenceable.name)}}-for-{{kebab_case to_referenceable.name}}.ts{{¡if}}.hbs
- templates/ui-frameworks/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{kebab_case (plural to_referenceable.name)}}-for-{{kebab_case from_referenceable.name}}.ts{{¡if}}.hbs
- templates/ui-frameworks/lit/web-app/ui/package.json.hbs
This PR:
- Replaces `@change` events with `@input` events in lit template inputs
- Fixes bug with the Enum field type on lit templates
- Use optional chaining when calling `this.client?.on` method
> fix: Update lit templates

- src/scaffold/web_app/package_manager.rs
For existing hApps, the node_modules dir(s) will need to be deleted and this command ran while in the nix shell:
```sh
corepack prepare yarn@1.22.22 --activate
```
> revert to yarn v1.22.22 nixpkg

- Cargo.lock
- Cargo.toml
- src/file_tree.rs
- src/scaffold/collection/coordinator.rs
- src/scaffold/dna/coordinator.rs
- src/scaffold/dna/integrity.rs
- src/scaffold/entry_type/coordinator.rs
- src/scaffold/entry_type/definitions.rs
- src/scaffold/entry_type/integrity.rs
- src/scaffold/link_type/coordinator.rs
- src/scaffold/link_type/integrity.rs
- src/scaffold/zome.rs
- src/scaffold/zome/coordinator.rs
- src/scaffold/zome/integrity.rs
- src/templates.rs
- src/utils.rs
This PR ensures line comments are preserved on modifying or creating new rust files while running scaffold commands that do so.
While this PR addresses the problem, it does open up another issue which I think is tolerable for now: Developer manually written doc comments `///` will end up getting converted to line comments `//` on running scaffolding commands that modify this file. While the comments will still be retained, they will take on a different format. I think this minor hiccup is tolerable, I will open up another issue so that we can keep track of it an make developers aware of this peculiarity.
Extra changes:
- [Move important scaffold functions to the top of the module for easy access](https://github.com/holochain/scaffolding/pull/382/commits/f7c01e5f65ebb6773be8b8ec39b4559cdbbb …
> fix: preserve line comments on creating/ modifying rust code

- flake.nix
- src/templates/collection.rs
- src/templates/entry_type.rs
- src/templates/link_type.rs
This PR optimizes the local development nix flake to only include nixpkgs it requires in its devshell
> fix: Optimize nix flake

- src/scaffold/entry_type/definitions.rs
- src/scaffold/entry_type/fields.rs
- src/utils.rs
This PR introduces the following changes:
- Improves enum field_type selection, the field_name is assumed to be the label of the enum to avoid unnecessary prompts (closes https://github.com/holochain/Components/issues/68)
- Updates how we prompt users for field types, rather than asking them for the type first, we now ask them for the name of the field then the type.
- Add the option that allows the user to re-start building of their entry-type through a recursive call to `choose_fields`, incase there was an error or mistake when creating a field for their entry type. This is a first step towards the replay functionality, further improvements to this can be made with (a) separate PR(s) i.e to modify/add/delete specific fields rather than starting over (first of …
> feat: Improve `hc-scaffold entry-type` developer experience

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/scaffold/app.rs
- src/scaffold/entry_type/definitions.rs
- src/templates/coordinator.rs
This PR cleans up holochain dependency usage in the following ways:
- Removes unused `holochain_utils` crate; this dependency was only used with a single error variant which was not converted from anywhere in the code
- Replaces `test_utils` feature from holochain with `hdk`.
> chore: Update holochain dependencies

- src/file_tree.rs
- src/scaffold/entry_type/integrity.rs
- src/scaffold/link_type/integrity.rs
- src/scaffold/zome.rs
- src/scaffold/zome/coordinator.rs
- src/utils.rs
Fixes #406
Fixes #413 (ensures `//` in URLs are not inadvertently replaced)
This PR also contains some additional code refactors to how the validate function codegen is handled
> fix: Fix misplaced doc comments

- Cargo.toml
- src/cli.rs
- src/cli/example.rs
- src/cli/web_app.rs
- src/scaffold/config.rs
- src/scaffold/web_app/template_type.rs
~This PR introduces a global `--skip-config-check` flag that does as the name suggests, to provide an option to skip reading from `hcScaffold` config in the root package.json file. Using this flag will be mostly beneficial to users who scaffolded their hApps with a nix wrapper based custom template.~
This PR skips writing scaffold configs for web-apps or examples scaffolded from nixified custom templates
Closes #247
> fix: Skip writing scaffold config for nixified custom templates

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- flake.nix
- guides/maintenance.md
- src/lib.rs
- src/versions.rs
TODOS:
This PR looks to close #412 and will also close #96
> feat: further improve ci runtime

- src/scaffold/entry_type/fields.rs
> feat: Add ability to go back and modify entry type fields

- templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs
- templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/Create{{pascal_case entry_type.name}}.svelte.hbs
- templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.svelte{{¡if}}{{¡each}}.hbs
- templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.svelte{{¡if}}.hbs
- templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.svelte.hbs
- templates/ui-frameworks/svelte/example/ui/src/App.svelte.hbs
- templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.svelte{{¡if}}.hbs
- templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.svelte{{¡if}}.hbs
- templates/ui-frameworks/svelte/web-app/ui/package.json.hbs
- templates/ui-frameworks/svelte/web-app/ui/src/App.svelte.hbs
- templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs
Fixes a race condition where Svelte components would try to access the client context when it's not yet defined.
> Fix race condition in Svelte template

- templates/ui-frameworks/svelte/web-app/ui/package.json.hbs
This reverts commit 3d80904fe65b4d9e78cc40af509a1623d7f0da17. It seems to introduce a packaging conflict.
> Revert update to vite-plugin-svelte for 0.4

- src/versions.rs
Just a cosmetic change, it would still work otherwise.
> chore: Bump hc-spin version to 0.400.0-rc.0

- src/cli/link_type.rs
- src/cli/web_app.rs
- src/utils.rs
> fix: gracefully handle number prefixed names

- templates/ui-frameworks/lit/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{kebab_case (plural ..¡entry_type.name)}}-for-{{kebab_case linked_from.name}}.ts{{¡if}}{{¡each}}.hbs
- templates/ui-frameworks/lit/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{kebab_case entry_type.name}}-detail.ts.hbs
- templates/ui-frameworks/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{kebab_case (plural from_referenceable.name)}}-for-{{kebab_case to_referenceable.name}}.ts{{¡if}}.hbs
- templates/ui-frameworks/lit/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{kebab_case (plural to_referenceable.name)}}-for-{{kebab_case from_referenceable.name}}.ts{{¡if}}.hbs
This PR fixes a ts error that was preventing `vite build` from running for lit templates
https://github.com/holochain/scaffolding/actions/runs/12763486851/job/35573852491#step:6:1006
> fix: lit template ts error

- src/templates/helpers/merge.rs
This PR adds support to more scopes for the `merge` helper. Previously, only "{}" was valid, but now it has been expanded to "{}", "[]", "()" and "<>". 
I encountered the need for this in a downstream project and thought it would be good to have it upstream. Let me know if I should rebase the PR to another branch, although I would need this merged in to 0.4 main.
> Expand merge helper scopes

- src/versions.rs
Bumps to `@holochain/hc-spin@0.500.0-dev.1` which is compatible with holochain 0.5.0-dev.21.
> bump hc-spin to 0.500.0-dev.1

- templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs
- templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/Create{{pascal_case entry_type.name}}.svelte.hbs
- templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#each entry_type.fields}}{{#if (and linked_from (not (eq linked_from.hash_type 'AgentPubKey') ) )}}{{pascal_case (plural ..¡entry_type.name)}}For{{pascal_case linked_from.name}}.svelte{{¡if}}{{¡each}}.hbs
- templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if crud.update}}Edit{{pascal_case entry_type.name}}.svelte{{¡if}}.hbs
- templates/ui-frameworks/svelte/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.svelte.hbs
- templates/ui-frameworks/svelte/example/ui/src/App.svelte.hbs
- templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and bidireccional (and to_referenceable (ne from_referenceable.hash_type 'AgentPubKey')))}}{{pascal_case (plural from_referenceable.name)}}For{{pascal_case to_referenceable.name}}.svelte{{¡if}}.hbs
- templates/ui-frameworks/svelte/link-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{#if (and to_referenceable (ne to_referenceable.hash_type 'AgentPubKey'))}}{{pascal_case (plural to_referenceable.name)}}For{{pascal_case from_referenceable.name}}.svelte{{¡if}}.hbs
- templates/ui-frameworks/svelte/web-app/ui/src/App.svelte.hbs
- templates/ui-frameworks/svelte/web-app/ui/src/ClientProvider.svelte.hbs
- templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs
Closes #466 
This PR adds measures to ensure the client is not accessible before its initialized. This is achieved by moving the client state to a global state and and sharing it across child components.
**Blocked by failing CI**
> fix(svelte): Ensure client is loaded before use

- flake.lock
- flake.nix
I was getting this warning when entering the nix shell:
```trace: warning: crane requires at least nixpkgs-24.11, supplied nixpkgs-24.05```
This PR bumps nixpkgs to 24.11
> build: bump nixpkgs for crane support

- templates/ui-frameworks/lit/web-app/ui/package.json.hbs
Fixes a warning about the deprecated `lodash.pick` package.
> Bump vite-plugin-checker version

- flake.lock
- flake.nix
- src/cli/custom-template/README.md
- src/cli/custom-template/flake.nix
- src/scaffold/app/nix.rs
- src/scaffold/web_app/package_manager.rs
Updates the nodejs version which results in npm 10.9.2 and should therefore hopefully fix #495 (see https://github.com/npm/cli/issues/7891#issuecomment-2492455892).
> Update nodejs version, update flake.lock
